project_path: ${hydra:runtime.cwd}
model: yolo
dataset: coco
model_name: model

#added by lorenzo
config:
  config_path: config
  templates_path: config/templates
  actual_config_path: config/actual_config

preproc:
  preprocessed_annotation: dataset.json
  orig:
    img_path: data/orig/images
  augmentation:
    img_path: data/coco/aug_images #Added by Lorenzo, ask Marco if ok -> used in split1.py, run_augmentation.py, split2.py
  img_size:
    width: 640
    height: 640
  split_percentage: 0.6 #Added by Lorenzo, ask Marco if ok -> used in split1.py and split2.py

datasets:
  n_classes: 3
  color_channels: 3
  labels:
    - 0
    - 1
    - 2
  class_name:
    - 'neoplastic'
    - 'aphthous'
    - 'traumatic'
  class_file: classes.txt #Added by Lorenzo, ask Marco if ok -> used in coco_to_yolo.py
  path: ${hydra:runtime.cwd}/data/
  img_path: images/
  original_data: orig/
  filenames:
    dataset: coco_dataset.json
  dataset_type: train  #Added by Lorenzo, ask Marco if ok -> used in coco_to_yolo.py
  datasets_path:
    coco:
      folder: coco
      train: coco/train.json
      val: coco/val.json
      test: coco/test.json
    yolo:
      folder: yolo
      train: yolo/train
      val: yolo/val
      test: yolo/test


#added by lorenzo
yolo:
  yolo_templates:
    model_template: yolov8-model-template.yaml
    data_template: yolov8-data-template.yaml
  yolo_config:
    model_config: yolov8-model.yaml
    data_config_train: yolov8-data.yaml
    data_config_test: yolov8-data-test.yaml
  yolo_model: yolov8n.pt
  parameters:
    device: 0
    output_dir: outputs/yolo/model_outputs
  yolo_model_path: train/weights/best.pt
  yolo_detect_output_path: outputs/yolo/model_results_on_test


#added by lorenzo
fastercnn:
  parameters:
    train_dataset_name: oralcancer_train
    val_dataset_name: oralcancer_val
    test_dataset_name: oralcancer_test
    config_file_path: COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml
    checkpoint_url: COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml
    output_dir: outputs/fastercnn/model_outputs
    device: cuda
  fastercnn_model_path: best_model.pth
  fastercnn_detect_output_path: outputs/fastercnn/model_results_on_test

detr:
  detr_path: detr
  parameters:
    dataset_file: custom
    coco_path: data/coco
    output_dir: outputs/detr
    logs_dir: training_logs
    device: cuda
    feature_extractor: facebook/detr-resnet-50
    lr_backbone: 1e-05
    gradient_clip_val: 0.1
  detr_model_path: model.pth
  detr_detect_output_path: outputs/detr/model_results_on_test




training:
  wandb: false
  lr: 5e-5
  epochs: 200
  batch: 8
  val_batch: 2
  early_stopping:
    monitor: val_loss
    patience: 5
  weight_decay: 0.0001
  optimizer: Adam #added by lorenzo
  workers: 8 #added by lorenzo
  img_size: 640 #added by lorenzo

test:
  confidence_threshold: 0.2
  iou_threshold: 0.5

models:
  path: ${hydra:runtime.cwd}/models
    

wandb:
  entity: mlpi
  project: oral
  tag: ""
