project_path: ${hydra:runtime.cwd}
model: fasetRCNN
dataset: coco
model_name: model

preproc:
  preprocessed_annotation: dataset.json
  orig:
    img_path: data/orig/images
  augmentation:
    img_path: data/coco/aug_images #Added by Lorenzo, ask Marco if ok -> used in split1.py, run_augmentation.py, split2.py
  img_size:
    width: 640
    height: 640
  split_percentage: 0.6 #Added by Lorenzo, ask Marco if ok -> used in split1.py and split2.py

datasets:
  n_classes: 3
  color_channels: 3
  labels:
    - 0
    - 1
    - 2
  class_name:
    - 'neoplastic'
    - 'aphthous'
    - 'traumatic'
  class_file: classes.txt #Added by Lorenzo, ask Marco if ok -> used in coco_to_yolo.py
  path: ${hydra:runtime.cwd}/data/
  img_path: images/
  original_data: orig/
  filenames:
    dataset: coco_dataset.json
  dataset_type: train  #Added by Lorenzo, ask Marco if ok -> used in coco_to_yolo.py


training:
  wandb: false
  lr: 1e-3
  epochs: 150
  batch: 64
  early_stopping:
    monitor: val_loss
    min_delta: 0.0005
    patience: 10


models:
  path: ${hydra:runtime.cwd}/models
    

wandb:
  entity: mlpi
  project: oral
  tag: ""
