project_path: ${hydra:runtime.cwd}
model: fasetRCNN
dataset: coco
model_name: model
os_distrib: windows #added by lorenzo

#added by lorenzo
config:
  config_path: config
  templates_path: config/templates
  actual_config_path: config/actual_config

preproc:
  preprocessed_annotation: dataset.json
  orig:
    img_path: data/orig/images
  augmentation:
    img_path: data/coco/aug_images #Added by Lorenzo, ask Marco if ok -> used in split1.py, run_augmentation.py, split2.py
  img_size:
    width: 640
    height: 640
  split_percentage: 0.6 #Added by Lorenzo, ask Marco if ok -> used in split1.py and split2.py

datasets:
  n_classes: 3
  color_channels: 3
  labels:
    - 0
    - 1
    - 2
  class_name:
    - 'neoplastic'
    - 'aphthous'
    - 'traumatic'
  class_file: classes.txt #Added by Lorenzo, ask Marco if ok -> used in coco_to_yolo.py
  path: ${hydra:runtime.cwd}/data/
  img_path: images/
  original_data: orig/
  filenames:
    dataset: coco_dataset.json
  dataset_type: train  #Added by Lorenzo, ask Marco if ok -> used in coco_to_yolo.py
  datasets_path:
    coco:
      train: coco/train.json
      val: coco/val.json
      test: coco/test.json
    yolo:
      train: yolo/train
      val: yolo/val
      test: yolo/test


#added by lorenzo
yolo:
  yolo_templates:
    model_template: yolov8-model-template.yaml
    data_template: yolov8-data-template.yaml
  yolo_config:
    model_config: yolov8-model.yaml
    data_config: yolov8-data.yaml
  yolo_model: yolov8n.pt
  parameters:
    device: 0
    output_dir: outputs/yolo/model_outputs
  yolo_model_path: train/weights/best.pt
  yolo_detect_output_path: outputs/yolo/model_results_on_test


#added by lorenzo
fastercnn:
  parameters:
    train_dataset_name: oralcancer_train
    val_dataset_name: oralcancer_val
    test_dataset_name: oralcancer_test
    config_file_path: COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml
    checkpoint_url: COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml
    output_dir: outputs/fastercnn/model_outputs
    device: cuda
  fastercnn_model_path: model_final.pth
  fastercnn_detect_output_path: outputs/fastercnn/model_results_on_test

detr:
  detr_path: detr
  detr_main_path: detr/main.py
  parameters:
    dataset_file: coco
    coco_path: data/coco
    output_dir: outputs/detr/model_outputs
    device: cuda
    resume: https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth




training:
  wandb: false
  lr: 1e-3
  epochs: 50
  batch: 8
  early_stopping:
    monitor: val_loss
    min_delta: 0.0005
    patience: 3

  optimizer: SGD #added by lorenzo
  workers: 8 #added by lorenzo
  img_size: 640 #added by lorenzo

test:
  confidence_threshold: 0.2
  iou_threshold: 0.5

models:
  path: ${hydra:runtime.cwd}/models
    

wandb:
  entity: mlpi
  project: oral
  tag: ""
