# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
train: ../data/yolo/train  # train images (relative to 'path') 128 images
val: ../data/yolo/val  # val images (relative to 'path') 128 images
test: ../data/yolo/test # test images (optional)

names: ["neoplastic", "aphthous", "traumatic"]